# Generated by Django 2.2.12 on 2020-04-11 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('pseudo', models.CharField(max_length=1)),
                ('pwd', models.CharField(max_length=30)),
                ('amis', models.ManyToManyField(related_name='_personne_amis_+', to='dinyadchat.personne')),
            ],
        ),
        migrations.CreateModel(
            name='recepteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinyadchat.personne')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinyadchat.personne')),
                ('recpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinyadchat.recepteur')),
            ],
        ),
    ]
